# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- release

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: $(System.DefaultWorkingDirectory)'/JobQuestTracker.Frontend

- script: |
    npm run build
  displayName: 'npm build'
  workingDirectory: $(System.DefaultWorkingDirectory)'/JobQuestTracker.Frontend

- task: CopyFiles@2
  inputs:
    Contents: $(System.DefaultWorkingDirectory)'/JobQuestTracker.Frontend/build/** # Pull the build directory (React)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
    ArtifactName: 'www' # output artifact named www

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'PlaygroundSubscription (e39b505e-2176-471d-b5a0-62d117076d8a)'
    appType: 'webAppLinux'
    WebAppName: 'JobQuestTracker'
    deployToSlotOrASE: true
    ResourceGroupName: 'JobQuestTracker-ResourceGroup'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
