# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: |
      echo  '$(System.DefaultWorkingDirectory)'
      dir

- task: CmdLine@2
  inputs:
    script: |
      npm install
      npm run build
    workingDirectory: 'JobQuestTracker.Frontend'
  displayName: 'npm install and build'

- task: CmdLine@2
  inputs:
    script: |
      echo  '$(System.DefaultWorkingDirectory)'
      dir
    workingDirectory: JobQuestTracker.Frontend
  displayName: list what is in Frontend folder after build

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/JobQuestTracker.Frontend/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'PlaygroundSubscription (e39b505e-2176-471d-b5a0-62d117076d8a)'
    appType: 'webAppLinux'
    WebAppName: 'JobQuestTracker'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'